# Generated by Django 5.0.7 on 2024-07-21 05:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
