# Generated by Django 5.0.7 on 2024-07-22 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_owner",
        ),
    ]
