# Generated by Django 5.0.7 on 2024-07-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
    ]
